name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mentor_marketing.jpg
    - assets/mentor_finanzas.jpg
    - assets/mentor_tecnologia.jpg
    - assets/mentor_ventas.jpg

    

  
